Remove OpenCV installation and commented out unused code

diff --git a/SBR_SERV/object_detector/dockerfile b/SBR_SERV/object_detector/dockerfile
--- a/SBR_SERV/object_detector/dockerfile
+++ b/SBR_SERV/object_detector/dockerfile
@@ -17,7 +17,7 @@ RUN apt-get install -y --no-install-recommends \
         qtbase5-dev 
 RUN add-apt-repository --remove "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" && \
     apt-get update && \
-    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
+    # apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
     apt-get install -y --no-install-recommends \
         cmake \
         nano \
@@ -31,14 +31,14 @@ RUN add-apt-repository --remove "deb https://apt.kitware.com/ubuntu/ $(lsb_relea
         gstreamer1.0-plugins-ugly \
         libgstreamer-plugins-base1.0-dev \
         libgstreamer-plugins-good1.0-dev \
-        libgstreamer-plugins-bad1.0-dev  \
+        # libgstreamer-plugins-bad1.0-dev  \
         gstreamer1.0-plugins-rtp
 
 WORKDIR /sbr
 
 # Clone and build jetson-utils
-RUN git clone https://github.com/dusty-nv/jetson-utils
-RUN cd jetson-utils && mkdir build && cd build && cmake ../ && make -j$(nproc) && make install && ldconfig
+# RUN git clone https://github.com/dusty-nv/jetson-utils
+# RUN cd jetson-utils && mkdir build && cd build && cmake ../ && make -j$(nproc) && make install && ldconfig
 
 # Copy source code
 RUN rm -rf src
