Update Dockerfile dependencies and install Gstreamer

diff --git a/SBR_SERV/object_detector/dockerfile b/SBR_SERV/object_detector/dockerfile
--- a/SBR_SERV/object_detector/dockerfile
+++ b/SBR_SERV/object_detector/dockerfile
@@ -1,18 +1,39 @@
 FROM nvcr.io/nvidia/l4t-base:r36.2.0 as dev
 
+RUN apt-get update
+
+# Install dependencies: https://github.com/dusty-nv/jetson-inference/blob/master/CMakePreBuild.sh
+RUN apt-get install -y --no-install-recommends \
+		dialog \
+		libglew-dev \
+		glew-utils \
+		gstreamer1.0-libav \
+		gstreamer1.0-nice \
+		libgstreamer1.0-dev \
+		libgstrtspserver-1.0-dev \
+		libglib2.0-dev \
+		libsoup2.4-dev \
+		libjson-glib-dev \
+		python3-pip \
+		python3-packaging \
+		qtbase5-dev
+
+RUN apt-get install -y --no-install-recommends \
+		libgstreamer-plugins-base1.0-dev \
+		libgstreamer-plugins-good1.0-dev \
+		libgstreamer-plugins-bad1.0-dev
+
+RUN apt-get install -y \
+        libpython3-dev \ 
+        python3-numpy
+
 # Install Gstreamer: https://github.com/dusty-nv/jetson-containers/blob/master/packages/gstreamer/Dockerfile
-RUN apt-get update && \
-    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
+RUN apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
     apt-get install -y --no-install-recommends \
-        dialog libglew-dev \
-        glew-utils \
-        libgstrtspserver-1.0-dev \
-        libglib2.0-dev \
-        libsoup2.4-dev \
-        libjson-glib-dev \
-        qtbase5-dev \
+        cmake \
+        nano \
+        mesa-utils \
         lsb-release \
-        libgstreamer1.0-dev \
         gstreamer1.0-tools \
         gstreamer1.0-libav \
         gstreamer1.0-rtsp \
@@ -22,35 +43,11 @@ RUN apt-get update && \
         libgstreamer-plugins-base1.0-dev \
         libgstreamer-plugins-good1.0-dev \
         libgstreamer-plugins-bad1.0-dev \
-        libgstrtspserver-1.0-0 \
+        gstreamer1.0-plugins-rtp \
         python3-gi \
-        python3-gst-1.0 \
-		gstreamer1.0-plugins-rtp 
+		python3-gst-1.0 \
+        libgstrtspserver-1.0-0 \
 
-
-RUN apt-get install -y --no-install-recommends \
-        git \
-		dialog \
-		libglew-dev \
-		glew-utils \
-		gstreamer1.0-libav \
-		libgstreamer1.0-dev \
-		libgstrtspserver-1.0-dev \
-		libglib2.0-dev \
-		libsoup2.4-dev \
-		libjson-glib-dev \
-		python3-pip \
-		qtbase5-dev
-
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
-		    libglew-dev \
-		    glew-utils \
-		    libsoup2.4-dev \
-		    libjson-glib-dev \
-		    libgstrtspserver-1.0-dev \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
 
 # Copy Gstreamer in a temporary directory
 # RUN cp -r /usr/include/gstreamer-1.0 /tmp
@@ -73,7 +70,7 @@ RUN apt-get update && \
 
 # Clone and build jetson-utils
 RUN mkdir jetson-utils_build && \ 
-    git clone https://github.com/dusty-nv/jetson-utils && \ 
+    git clone --depth=1 https://github.com/dusty-nv/jetson-utils && \ 
     cd jetson-utils && \ 
     mkdir build && \ 
     cd build && \ 
